### ISSUE TITLE
can supCon loss used in multi-label classification?

### ISSUE THREAD

**Issue by chuanhuayang** [ivanpanshin/SupCon-Framework#27]
I have a text multi-label classification task，can i use supCon loss ?
supCon loss is accumulated by every label view，for example:
`
  batch data label = [[1, 0, 1],
    [0, 1, 1],
    [1, 1, 0],
    [0, 1, 1]
  ]
`
from view label 0, positive examples = {0, 2}，negative samples = {1, 3}
from view label 1, positive examples = {1, 2,3}, negative samples = {0}
from view label 2, positive examples = {0, 1, 2}, negative samples = {2}

is this setting here reasonable ？

**Comment by ivanpanshin** [comment]
Hey man 

Good question. I'd have to check the math, but I don't think it will work out of the box. The only piece of evidence that I can come up with at the spot is 

> "Similarly, supervised contrastive loss (SupCon) [10] could not be directly applied to handle the multilabel scenario" 

([link](https://arxiv.org/pdf/2105.09401.pdf))

**Comment by chuanhuayang** [comment]
thank you very much，i will read this paper in detail !
